import Head from "next/head";
import type { NextPage } from "next";
import {
  Container,
  Stack,
  VStack,
  HStack,
  Heading,
  Text,
  Box,
  Center,
  Image as ProfilePic,
} from "@chakra-ui/react";
import teamInfo from "../components/data/teamInfo";

const TEAM_MEMBER: [string, string, string][] = [
  ["Ilham Bara", teamInfo.member[1], "Lead"],
  ["Amin Rizki", teamInfo.member[2], "Member"],
  ["Sulthan Rafif", teamInfo.member[3], "Member"],
];

const Team: NextPage = () => {
  return (
    <>
      <Head>
        <title>Core Team &ndash; XTRA</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container as="section" maxW="container.lg" h="100%" py={4}>
        <VStack
          w="100%"
          spacing="1.5rem"
          alignItems="flex-start"
          mt={["6rem", "17vh"]}
          lineHeight={1.8}
        >
          <Heading
            as="h1"
            fontSize={["1.5rem", "3rem"]}
            lineHeight="1.5"
            textTransform="capitalize"
          >
            {teamInfo.title}
          </Heading>

          <Text fontSize="lg">{teamInfo.desc}</Text>
        </VStack>

        <Stack direction={["column", "row"]} align="center" spacing={8}>
          {TEAM_MEMBER.map(([name, ava, role]) => (
            <Box
              width={["75%", "25%"]}
              key={name}
              justifyContent="center"
              bg="gray.900"
              my={8}
              p={4}
              lineHeight={1.8}
              boxShadow="lg"
              textAlign={["center", "left"]}
            >
              <Center>
                <ProfilePic
                  borderRadius="full"
                  bgColor="gray.800"
                  boxSize="180px"
                  src={ava}
                  alt={name}
                />
              </Center>
              <Heading as="h2" fontSize="2xl" fontWeight="semibold" py={4}>
                {name}
              </Heading>
              <Text fontSize="sm" opacity={0.65}>
                {role}
              </Text>
            </Box>
          ))}
        </Stack>

        <Text fontSize="sm" opacity={0.5} my={8}>
          Note: credit of avatar goes to Apple Memoji.
        </Text>
      </Container>
    </>
  );
};

export default Team;
