import { Button } from "@chakra-ui/button";
import { useColorMode, useColorModeValue } from "@chakra-ui/color-mode";
import { Box, Container, Heading, Link, useToken } from "@chakra-ui/react";
import { FaMoon, FaSun } from "react-icons/fa";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import data from "../data/data.json";

const Home: NextPage = () => {
	const { colorMode, toggleColorMode } = useColorMode();

	const [lightColor, darkColor] = useToken("colors", [
		"gray.900",
		"gray.50",
	]) as [string, string];

	const bgSvg = useColorModeValue(darkColor, lightColor);

	const color = useColorModeValue("blue.600", "yellow.300");

	return (
		<>
			<Box
				as="svg"
				pos="absolute"
				viewBox="0 0 1440 240"
				zIndex={-1}
				transform="rotate(180deg)"
			>
				<path
					fill={bgSvg}
					fillOpacity="1"
					d="M0,64L48,58.7C96,53,192,43,288,32C384,21,480,11,576,48C672,85,768,171,864,197.3C960,224,1056,192,1152,149.3C1248,107,1344,53,1392,26.7L1440,0L1440,320L1392,320C1344,320,1248,320,1152,320C1056,320,960,320,864,320C768,320,672,320,576,320C480,320,384,320,288,320C192,320,96,320,48,320L0,320Z"
				/>
			</Box>

			<Container maxW="container.xl" maxH="100vh" h="100%">
				<Head>
					<title>XTRA &ndash; (development)</title>
					<meta name="description" content="Generated by create next app" />
					<link rel="icon" href="/favicon.ico" />
				</Head>

				<main className={styles.main}>
					<Button variant="outline" onClick={toggleColorMode}>
						{colorMode === "light" ? <FaMoon /> : <FaSun />}
					</Button>

					<Heading
						as="h1"
						fontWeight="medium"
						fontSize="5xl"
						mt={6}
						textAlign="center"
					>
						Welcome to The{" "}
						<Link href="#" color={color}>
							{"{HomePage}!"}
						</Link>
					</Heading>

					<div className={styles.grid}>
						{data.map((info) => (
							<a href="#" className={styles.card} key={info.id}>
								<h2>Page {info.id} &rarr;</h2>
								<p>{info.desc}</p>
							</a>
						))}
					</div>
				</main>
			</Container>
		</>
	);
};

export default Home;
