import { Button } from "@chakra-ui/button";
import { useColorMode, useColorModeValue } from "@chakra-ui/color-mode";
import {
  Box,
  Container,
  Heading,
  Icon,
  LightMode,
  Link,
  Text,
  useToken,
  useBreakpointValue,
  VStack,
  HStack,
  Grid,
  Image,
} from "@chakra-ui/react";
import {
  FaMoon,
  FaSun,
  FaInstagram,
  FaFacebookSquare,
  FaYoutube,
  FaSteam,
} from "react-icons/fa";
import { IconType } from "react-icons/lib";
import type { NextPage } from "next";
import Head from "next/head";
import siteConfig from "../config/site";

const SOCIAL_LINKS: [string, string, IconType, string][] = [
  ["Instagram", siteConfig.socials.Instagram, FaInstagram, "pink"],
  ["Facebook", siteConfig.socials.Facebook, FaFacebookSquare, "facebook"],
  ["YouTube", siteConfig.socials.YouTube, FaYoutube, "red"],
  ["Steam", siteConfig.socials.Steam, FaSteam, "blackAlpha"],
];

const Home: NextPage = () => {
  const { colorMode, toggleColorMode } = useColorMode();

  const [lightColor, darkColor] = useToken("colors", [
    "gray.900",
    "gray.50",
  ]) as [string, string];

  const bgSvg = useColorModeValue(darkColor, lightColor);
  const color = useColorModeValue("gray.800", "yellow.300");

  const buttonSize = useBreakpointValue(["sm", "md", "lg"]);

  return (
    <>
      <Head>
        <title>XTRA &ndash; (development)</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box
        as="svg"
        pos="absolute"
        viewBox="0 0 1440 240"
        zIndex={-1}
        transform="rotate(180deg)"
      >
        <path
          fill={bgSvg}
          fillOpacity="1"
          d="M0,64L48,58.7C96,53,192,43,288,32C384,21,480,11,576,48C672,85,768,171,864,197.3C960,224,1056,192,1152,149.3C1248,107,1344,53,1392,26.7L1440,0L1440,320L1392,320C1344,320,1248,320,1152,320C1056,320,960,320,864,320C768,320,672,320,576,320C480,320,384,320,288,320C192,320,96,320,48,320L0,320Z"
        />
      </Box>

      <Container
        maxW="container.lg"
        maxH={["100%", "100vh"]}
        h="100%"
        py={[8, 4]}
      >
        <VStack w="100%" spacing="2rem" alignItems="flex-start">
          <Button variant="outline" onClick={toggleColorMode} my={6}>
            {colorMode === "light" ? <FaMoon /> : <FaSun />}
          </Button>

          <HStack w="100%">
            <Box borderRadius="lg">
              <Image
                boxSize={["75px", "100px"]}
                borderRadius="lg"
                src="https://raw.githubusercontent.com/official-xtra/dev-test-website/main/public/xtra.png"
                alt="xtra"
              />
            </Box>

            <VStack
              height="100px"
              alignItems="flex-start"
              justifyContent="center"
            >
              <Heading
                as="h1"
                fontWeight="bold"
                fontSize={["2.35rem", "5xl"]}
                textAlign="center"
                textTransform="uppercase"
                textColor="yellow.300"
                color={color}
              >
                Official X-TRA
              </Heading>

              <Text fontSize={["sm", "lg"]} fontWeight="medium" pl={1}>
                We are not just Solidarity, but we are Family
              </Text>
            </VStack>
          </HStack>

          <VStack
            w="100%"
            alignItems="flex-start"
            textAlign="left"
            spacing="md"
          >
            <Heading
              as="h1"
              fontSize={["1.65rem", "3.25rem"]}
              lineHeight="1.5"
              textTransform="capitalize"
            >
              X-TRA is a Group of People Graduated from AR-RAHMAT Junior High
              School
            </Heading>
            <Text fontSize={["md", "3xl"]} textColor="gray.400" mt={4}>
              Let{"'"}s get acquainted and have a good connection with us! Feel
              free to greet us via the social media links below.
            </Text>
          </VStack>

          <LightMode>
            <Grid
              width={{ base: "100%", lg: "75%" }}
              templateColumns={{ base: "repeat(2, 1fr)", md: "repeat(4, 1fr)" }}
              gap={{ base: 4, lg: 6 }}
            >
              {SOCIAL_LINKS.map(([btnName, href, AsIcon, colorScheme]) => (
                <Button
                  key={btnName}
                  as="a"
                  colorScheme={colorScheme}
                  href={href}
                  leftIcon={<Icon as={AsIcon} boxSize={[4, 5, 6]} />}
                  size={buttonSize}
                  target="_blank"
                >
                  {btnName}
                </Button>
              ))}
            </Grid>
          </LightMode>
        </VStack>
      </Container>

      <Box as="svg" pos="absolute" viewBox="0 0 1440 280" zIndex={-1}>
        <path
          fill={bgSvg}
          fillOpacity="1"
          d="M0,64L48,58.7C96,53,192,43,288,32C384,21,480,11,576,48C672,85,768,171,864,197.3C960,224,1056,192,1152,149.3C1248,107,1344,53,1392,26.7L1440,0L1440,320L1392,320C1344,320,1248,320,1152,320C1056,320,960,320,864,320C768,320,672,320,576,320C480,320,384,320,288,320C192,320,96,320,48,320L0,320Z"
        />
      </Box>
    </>
  );
};

export default Home;
